"""Cassette-backed contract tests for ``EmbyServer`` vendor-API calls.

Pins the URL contract for Emby's exact-Path filter and Pass-0/1/2
fallbacks. Specifically catches:
- Audit L2 — ``IncludeItemTypes=Movie,Episode`` filter (a non-video
  item indexed at the same Path could otherwise return wrong id).
- The Path= filter URL shape and 200 OK + empty Items response on
  miss.
- HIT path: Pass 0 ``NameStartsWith=<first-word>`` fast path returns
  the right item id without hitting Pass 1+2.
- Negative short-circuit: when Pass 0 found 0 candidates with a valid
  prefix and a known ``parent_id``, we DO NOT fall through to the
  expensive Pass 1 ``searchTerm`` query (perf #44).

The cassette captures the EXACT request URLs that Emby accepts, so
any drift (param renamed, removed, type changed) fails loud.
"""

from __future__ import annotations

import os

import pytest

from media_preview_generator.servers import EmbyServer, Library, ServerConfig, ServerType

pytestmark = [pytest.mark.vcr]

_MISS_PATH = "/data/Movies/MPG_Cassette_Sentinel_DoesNotExist_99999.mkv"
# HIT scenario uses the integration test stack's library mount + a
# known-indexed synthetic media file generated by
# ``tests/integration/generate_test_media.sh``. Path is fixed (not
# pulled from env) so cassette replay doesn't depend on env vars.
_HIT_LIBRARY_REMOTE_PATH = "/em-media/Movies"
_HIT_PATH = f"{_HIT_LIBRARY_REMOTE_PATH}/Test Movie H264 (2024)/Test Movie H264 (2024).mkv"
# Cold-miss path: a synthetic basename whose FIRST WORD won't match
# any series in the test library, exercising Pass 0's
# "NameStartsWith returned 0 candidates → short-circuit" branch
# (perf #44). Picks an obscure first word ("Zzzzzz") so the
# NameStartsWith query lands deterministically.
_PASS0_NEGATIVE_PATH = (
    f"{_HIT_LIBRARY_REMOTE_PATH}/Zzzzzz Nonexistent Show (2099)/Zzzzzz Nonexistent Show (2099) - S01E01 - Pilot.mkv"
)


@pytest.fixture
def emby_under_test():
    url = os.environ.get("EMBY_URL", "http://fake-emby.local:8096")
    token = os.environ.get("EMBY_TOKEN", "fake-token")
    user_id = os.environ.get("EMBY_USER_ID", "")
    cfg = ServerConfig(
        id="emby-vcr",
        type=ServerType.EMBY,
        name="Emby VCR",
        enabled=True,
        url=url,
        auth={"method": "api_key", "api_key": token, "user_id": user_id}
        if user_id
        else {"method": "api_key", "api_key": token},
        verify_ssl=False,
        libraries=[
            # Library remote_paths must include the test stack's
            # mount so the resolver's library-scoping helper finds a
            # matching ``parent_id`` and the recorded URL includes
            # ``ParentId=...``. Without this match, Pass 0/1 queries
            # are unscoped and the cassette URL contract changes.
            Library(id="1", name="Movies", remote_paths=("/data/Movies", _HIT_LIBRARY_REMOTE_PATH), enabled=True),
        ],
    )
    return EmbyServer(cfg)


class TestEmbyResolveOnePathContract:
    """Contract pins for the EmbyServer reverse-lookup chain.

    The MISS cassette captures Emby's ``GET /Items?Path=<exact>...``
    response when no item matches. Pins:
    - URL contains ``Path=<exact>`` AND
      ``IncludeItemTypes=Movie,Episode`` (audit L2).
    - ``X-Emby-Token`` header (scrubbed).
    - 200 OK with empty ``Items`` list.

    A regression that drops ``IncludeItemTypes`` would either
    cassette-miss (URL doesn't match) or re-record with a different
    URL shape — either way detection is loud.
    """

    def test_unknown_path_returns_none_via_path_filter(self, emby_under_test):
        item_id = emby_under_test._uncached_resolve_remote_path_to_item_id(_MISS_PATH)
        assert item_id is None

    def test_known_path_resolves_via_pass0_namestartswith(self, emby_under_test):
        """HIT cassette: a synthetic test movie indexed in the test stack
        resolves through Pass 0's ``NameStartsWith=<first-word>`` fast
        path, returning a non-empty item id. Pins:
        - The Pass-0 URL shape (``NameStartsWith=Test`` +
          ``IncludeItemTypes=Movie`` + ``ParentId=<lib>``).
        - The local-basename match logic: server returns Items keyed
          by Path, our ``_match`` picks the right one even though
          NameStartsWith returns multiple ``Test*`` candidates.
        """
        item_id = emby_under_test._uncached_resolve_remote_path_to_item_id(_HIT_PATH)
        assert item_id, "Test stack must have 'Test Movie H264 (2024)' indexed for this cassette"

    def test_pass0_negative_short_circuits_pass1(self, emby_under_test):
        """Perf #44: when Pass 0 ran with a valid ParentId-scoped prefix
        and got 0 candidates back, we DO NOT fall through to Pass 1's
        full-stem ``searchTerm`` query (the slow 30s scoring loop).

        Cassette pins exactly which URLs were dispatched. A regression
        that re-introduces the Pass-1 fall-through cassette-misses on
        replay (extra unexpected request).
        """
        item_id = emby_under_test._uncached_resolve_remote_path_to_item_id(_PASS0_NEGATIVE_PATH)
        assert item_id is None


class TestEmbyTriggerPathRefreshContract:
    """Contract pin for ``EmbyServer._trigger_path_refresh``.

    Emby's path-based scan-nudge is ``POST /Library/Media/Updated``
    with a JSON body
    ``{"Updates":[{"Path":"…","UpdateType":"Modified"}]}``. Same shape
    Sonarr/Radarr's own path-update notifier uses.

    A regression that renames the body field (``Path`` → ``path``,
    ``UpdateType`` → ``update_type``, ``Updates`` → ``items``) would
    leave Emby silent — endpoint returns 204 No Content regardless of
    payload validity, so the only safety net is the cassette URL +
    body shape pin.
    """

    def test_path_refresh_posts_library_media_updated(self, emby_under_test):
        emby_under_test._trigger_path_refresh(_HIT_PATH)
        # No return value to assert on — the cassette interaction IS
        # the assertion. A future regression that changes the URL or
        # body shape gets a cassette miss on replay (vcrpy enforces
        # exact request matching for replay).
