"""Plex Video Preview Generator

A tool for generating video preview thumbnails for Plex Media Server.
Supports GPU acceleration (NVIDIA, AMD, Intel, Windows) and CPU processing.
"""

import os
import uuid

# Ensure a stable Plex client identity to prevent "new device" notifications.
# Users can override these via environment variables before import if desired.
os.environ.setdefault(
    "PLEXAPI_HEADER_IDENTIFIER",
    uuid.uuid3(uuid.NAMESPACE_DNS, "PlexGeneratePreviews").hex,
)
os.environ.setdefault("PLEXAPI_HEADER_DEVICE_NAME", "PlexGeneratePreviews")


def _get_version() -> str:
    """Return package version from metadata, _version.py, or a dev fallback.

    Priority:
    1. importlib.metadata (installed package) -- unless it's the 0.0.0
       fallback that setuptools-scm writes when .git is absent at build time.
    2. _version.py generated by setuptools-scm (present in source tree).
    3. Hardcoded dev fallback.
    """
    try:
        import importlib.metadata

        ver = importlib.metadata.version("plex-generate-previews")
        if not ver.startswith("0.0.0"):
            return ver
    except Exception:
        pass

    try:
        from ._version import __version__ as scm_version

        return scm_version
    except (ImportError, AttributeError):
        pass

    return "0.0.0.dev0"


__version__ = _get_version()

__author__ = "stevezau"
__description__ = "Generate video preview thumbnails for Plex Media Server"
