"""Version file auto-generated by setuptools-scm.

When building from a Git checkout, setuptools-scm will write the
resolved PEP 440 version here. Do not edit manually.
"""

from typing import Tuple

__version__ = "2.3.0"
__version_tuple__: Tuple[int, int, int] = (2, 3, 0)
